version: "3.9"

services:
  db:
    image: postgres:14
    container_name: pg14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: dyps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: dyps-api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgrespw@db:5432/dyps
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
